import defaultImage from "../assets/hero-tutoring-optimized.webp";
import { getSupabaseClient } from "../auth/client.js";
import { mountAuthNavigation } from "../auth/session-ui.js";
const id=new URLSearchParams(location.search).get("id"),statusBox=document.querySelector("[data-status]"),content=document.querySelector("[data-content]"),likeButton=document.querySelector("[data-like]"),followButton=document.querySelector("[data-follow]"),commentForm=document.querySelector("[data-comment-form]"),commentInput=document.querySelector("[data-comment]"),feedback=document.querySelector("[data-feedback]"),commentsBox=document.querySelector("[data-comments]");let supabase,user,item,liked=false,following=false;
const category={grammar:"문법",reading:"독해",vocabulary:"어휘",exam:"시험 대비"};
function loginNext(){location.assign(`/login/?next=${encodeURIComponent(location.pathname+location.search)}`)}
function dateText(v){return new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"long",day:"numeric"}).format(new Date(v))}
function renderComments(rows){commentsBox.replaceChildren();if(!rows.length){commentsBox.textContent="첫 댓글을 남겨보세요.";return}rows.forEach(row=>{const el=document.createElement("article");el.className="comment";const p=document.createElement("p");p.textContent=row.body;const time=document.createElement("time");time.dateTime=row.created_at;time.textContent=`${row.author_id===user?.id?"나":"ELC 회원"} · ${dateText(row.created_at)}`;el.append(p,time);commentsBox.append(el)})}
async function refreshSocial(){const [{count},{data:comments}]=await Promise.all([supabase.from("item_likes").select("*",{count:"exact",head:true}).eq("item_id",id),supabase.from("item_comments").select("id,author_id,body,created_at").eq("item_id",id).order("created_at",{ascending:false})]);document.querySelector("[data-like-count]").textContent=count||0;renderComments(comments||[]);if(user){const {data:mine}=await supabase.from("item_likes").select("item_id").eq("item_id",id).eq("user_id",user.id).maybeSingle();liked=!!mine;likeButton.classList.toggle("active",liked);likeButton.firstChild.textContent=liked?"♥ 좋아요 ":"♡ 좋아요 ";if(item.author_id&&item.author_id!==user.id){const {data:follow}=await supabase.from("member_follows").select("following_id").eq("follower_id",user.id).eq("following_id",item.author_id).maybeSingle();following=!!follow;followButton.textContent=following?"팔로우 취소":"작성자 팔로우"}else{followButton.hidden=true}}}
async function initialize(){try{if(!/^[0-9a-f-]{36}$/i.test(id||""))throw new Error("수업 주소가 올바르지 않습니다.");supabase=await getSupabaseClient();const {data:s}=await supabase.auth.getSession();user=s.session?.user||null;await mountAuthNavigation();const {data,error}=await supabase.from("items").select("id,author_id,title,target_grades,description,category,schedule_text,location,material,status,image_url").eq("id",id).single();if(error||!data)throw new Error("수업을 찾을 수 없습니다.");item=data;document.querySelector("[data-image]").src=item.image_url||defaultImage;document.querySelector("[data-image]").alt=`${item.title} 대표 이미지`;document.querySelector("[data-category]").textContent=category[item.category]||"영어 수업";document.querySelector("[data-title]").textContent=item.title;document.querySelector("[data-description]").textContent=item.description;document.querySelector("[data-grades]").textContent=item.target_grades.map(n=>`중${n}`).join(" · ");document.querySelector("[data-schedule]").textContent=item.schedule_text;document.querySelector("[data-location]").textContent=item.location;document.querySelector("[data-material]").textContent=item.material||"확정 후 안내";statusBox.hidden=true;content.hidden=false;await refreshSocial()}catch(e){statusBox.textContent=e.message||"수업을 불러오지 못했습니다."}}
likeButton.addEventListener("click",async()=>{if(!user)return loginNext();likeButton.disabled=true;const q=supabase.from("item_likes");const {error}=liked?await q.delete().eq("item_id",id).eq("user_id",user.id):await q.insert({item_id:id,user_id:user.id});if(error)feedback.textContent="좋아요를 처리하지 못했습니다.";else await refreshSocial();likeButton.disabled=false});
followButton.addEventListener("click",async()=>{if(!user)return loginNext();followButton.disabled=true;const q=supabase.from("member_follows");const {error}=following?await q.delete().eq("follower_id",user.id).eq("following_id",item.author_id):await q.insert({follower_id:user.id,following_id:item.author_id});if(error)feedback.textContent="팔로우를 처리하지 못했습니다.";else await refreshSocial();followButton.disabled=false});
commentForm.addEventListener("submit",async e=>{e.preventDefault();if(!user)return loginNext();const body=commentInput.value.trim();if(!body){feedback.textContent="댓글 내용을 입력해 주세요.";return}const button=commentForm.querySelector("button");button.disabled=true;const {error}=await supabase.from("item_comments").insert({item_id:id,author_id:user.id,body});if(error)feedback.textContent="댓글을 등록하지 못했습니다.";else{commentInput.value="";feedback.textContent="";await refreshSocial()}button.disabled=false});initialize();
